### ISSUE TITLE
Magento eventually crashes after long term use of Zoom

### ISSUE THREAD

**Issue by sloth456** [ezramorse/Zoom-Magento-FPC#9]
Hi,

Zoom will work fine for several days with no issues until all of a sudden magento totally crashes and does not allow you to get to the backend or see the frontend (apart from those pages that are cached by zoom)

The only way to fix the issue is to delete he contents of var/zoom , var/cache and var/session

Once this is done the site runs good again.  The error report we get looks like this

a:5:{i:0;s:59:"Mage registry key "_singleton/core/resource" already exists";i:1;s:825:"#0 /usr/share/nginx/www/app/Mage.php(192): Mage::throwException('Mage registry k...')
#1 /usr/share/nginx/www/app/Mage.php(446): Mage::register('_singleton/core...', Object(Mage_Core_Model_Resource))
#2 /usr/share/nginx/www/app/code/core/Mage/Core/Model/Resource/Setup.php(141): Mage::getSingleton('core/resource')
#3 /usr/share/nginx/www/app/code/core/Mage/Core/Model/Resource/Setup.php(234): Mage_Core_Model_Resource_Setup->__construct('core_setup')
#4 /usr/share/nginx/www/app/code/core/Mage/Core/Model/App.php(408): Mage_Core_Model_Resource_Setup::applyAllUpdates()
#5 /usr/share/nginx/www/app/code/core/Mage/Core/Model/App.php(336): Mage_Core_Model_App->_initModules()
#6 /usr/share/nginx/www/app/Mage.php(640): Mage_Core_Model_App->run(Array)
#7 /usr/share/nginx/www/index.php(77): Mage::run('btn', 'website')
#8 {main}";s:3:"url";s:39:"/burton-gig-bag-estate-plaid-156cm-2012";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:7:"default";}

**Comment by newyorkwebdesign** [comment]
YES! Someone has the same problem as me. It seems that after GoogleBot crawls the entire site my server gets a bit bloated by all the 200 gigs worth of cached pages. Any solution?

**Comment by sloth456** [comment]
It's been 9 months since I posted this thread.. I don't remember exactly what I did to fix this.  I don't ever remembering getting anything like 200 gigs worth of cached pages.  I think in the end I just bought more webspace,  200 gigs seems like a lot! I'm sure I only generated maybe 10 gigs worth of cached content at max and that was with about 3000 products.

Personally, if you still have the choice I'd recommend not using magento at all.  Even after 9 months I still am not satisfied with magento in general.

**Comment by newyorkwebdesign** [comment]
thanks!

David Radovanovic
WhatsTheBigIdea.com, Inc.
-- Web Design and Graphic Design Services
100 Dock Street
Saugerties, NY 12477
(845) 247-0909
@thebigdesign
